disabled_rules:
 - trailing_whitespace
 - line_length
 - opening_brace
excluded:
  - Carthage/

force_try: warning
force_cast: warning
colon:
  apply_to_dictionaries: false
statement_position:
   statement_mode: uncuddled_else
variable_name:
  excluded:
    - id
    - to

type_body_length: 
  warning: 900
  error: 1300

function_body_length: 
  warning: 100

file_length:
  warning: 900
  error: 1300